version: 2

sources:
  - name: FIVETRAN_DATABASE
    database: FIVETRAN_DATABASE
    schema: RAW_DATA
    tables:
      - name: OLIST_ORDERS_DATASET
      - name: OLIST_ORDER_PAYMENTS_DATASET
      - name: OLIST_ORDER_ITEMS_DATASET
      - name: OLIST_PRODUCTS_DATASET
      - name: PRODUCT_CATEGORY_NAME_TRANSLATION
      - name: OLIST_CUSTOMERS_DATASET       
    
      
